### ISSUE TITLE
missing headers (conio.h/i86.h/dos.h)  maybe others trying to build with ia16

### ISSUE THREAD

**Issue by neozeed** [FrenkelS/Doom8088#45]
Im trying to build on Ubuntu 22.04 with that fancy ia16 toolchain

```
   sudo add-apt-repository ppa:tkchia/build-ia16
   sudo apt-get update
   sudo apt-get install gcc-ia16-elf
   sudo apt-get install nasm
```

So far so good, but it seems that there is some msdos specific stuff it should have?

```
i_vmodey.c:26:19: fatal error: conio.h: No such file or directory
compiler.h:24:17: fatal error: i86.h: No such file or directory
z_zone.c:25:17: fatal error: dos.h: No such file or directory
```

Sorry for being such a n00b, I can't seem to find much of anything definitive on using this toolchain.

**Comment by FrenkelS** [comment]
I think you also need [libi86](https://gitlab.com/tkchia/libi86). I'll update the documentation if that solves this issue.

**Comment by neozeed** [comment]
After messing with building the lib from source I did eventually find it's just a library that can be added from tkchia's repo:

`sudo apt-get install libi86-ia16-elf`

I was then able to build from source, and get a working EXE!

Thanks!
